        /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jp32.views;
//import java.awt.AWTEvent;

import com.jp32.controllers.StSignUpController;

/**
 *
 * @author Win
 */
public class A_Signup extends javax.swing.JFrame {
    
    private StSignUpController stSignUpController=new StSignUpController();

    
    public A_Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextfname = new javax.swing.JTextField();
        jTextlname = new javax.swing.JTextField();
        jTextuname = new javax.swing.JTextField();
        jPassword1Field = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTextMemberId = new javax.swing.JTextField();
        jPassword2Field = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextcontactnum = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBoxpost = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextdegree = new javax.swing.JTextField();
        jComboBoxfaculty = new javax.swing.JComboBox<>();
        jLabel1RepStatus = new javax.swing.JLabel();
        jCmbuserType = new javax.swing.JComboBox<>();
        jCheckBoxRepStatus = new javax.swing.JCheckBox();

        jTextField5.setText("jTextField5");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(6, 20));
        setPreferredSize(new java.awt.Dimension(455, 650));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SignUp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 310, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 150, 70, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 200, 70, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 350, 70, 20);

        jTextfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextfnameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextfname);
        jTextfname.setBounds(170, 160, 110, 22);

        jTextlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextlnameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextlname);
        jTextlname.setBounds(170, 200, 110, 20);

        jTextuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextunameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextuname);
        jTextuname.setBounds(170, 310, 110, 22);

        jPassword1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword1FieldActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword1Field);
        jPassword1Field.setBounds(170, 350, 110, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("MemberID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 120, 70, 20);

        jTextMemberId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMemberIdActionPerformed(evt);
            }
        });
        getContentPane().add(jTextMemberId);
        jTextMemberId.setBounds(170, 120, 110, 22);

        jPassword2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword2FieldActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword2Field);
        jPassword2Field.setBounds(170, 390, 110, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Confirm Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 380, 120, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("User Type");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 420, 80, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Contact Number");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 520, 100, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Post");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 500, 40, 20);

        jTextcontactnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcontactnumActionPerformed(evt);
            }
        });
        getContentPane().add(jTextcontactnum);
        jTextcontactnum.setBounds(160, 530, 120, 22);

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 555, 90, 30);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(80, 560, 90, 30);

        jComboBoxpost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "President", "Treasurer", "Vice President", "Secretary" }));
        jComboBoxpost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxpostMouseClicked(evt);
            }
        });
        jComboBoxpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxpostActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxpost);
        jComboBoxpost.setBounds(170, 500, 90, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Faculty");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 230, 90, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("DegreeProgram");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 270, 120, 20);

        jTextdegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextdegreeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextdegree);
        jTextdegree.setBounds(170, 270, 110, 22);

        jComboBoxfaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FOB", "FOC", "FOE", " " }));
        getContentPane().add(jComboBoxfaculty);
        jComboBoxfaculty.setBounds(170, 240, 70, 20);

        jLabel1RepStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1RepStatus.setText("Rep Status");
        getContentPane().add(jLabel1RepStatus);
        jLabel1RepStatus.setBounds(50, 470, 70, 15);

        jCmbuserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Rep. Student" }));
        getContentPane().add(jCmbuserType);
        jCmbuserType.setBounds(170, 420, 110, 22);

        jCheckBoxRepStatus.setText("Yes");
        getContentPane().add(jCheckBoxRepStatus);
        jCheckBoxRepStatus.setBounds(170, 460, 81, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextunameActionPerformed

    private void jTextlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextlnameActionPerformed

    private void jTextMemberIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMemberIdActionPerformed
       
               
                        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMemberIdActionPerformed

    private void jPassword1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword1FieldActionPerformed

    private void jTextfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextfnameActionPerformed

    private void jPassword2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword2FieldActionPerformed

    private void jComboBoxpostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxpostMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxpostMouseClicked

    private void jTextdegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextdegreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextdegreeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextcontactnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcontactnumActionPerformed
       //allow only numbers
       /*if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
       }*/
       
    }//GEN-LAST:event_jTextcontactnumActionPerformed

    private void jComboBoxpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxpostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxpostActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String userid=jTextMemberId.getText();
       String firstName=jTextfname.getText();
       String lastName=jTextlname.getText();
       String faculty= (String)jComboBoxfaculty.getSelectedItem();
       String dp=jTextdegree.getText();
       String username=jTextuname.getText();
       String password=String.valueOf(jPassword1Field.getPassword());
       String post=(String)jComboBoxpost.getSelectedItem();
       String userType=(String)jCmbuserType.getSelectedItem();
        System.out.println(userType);
        /*if(jRadioButtonfemale.isSelected()){
                   userType="student rep";
               }*/
       String Contactdt=jTextcontactnum.getText();
       //String repassword=String.valueOf(jPassword2Field.getPassword());
       
       String rpstatus ="No";
       if (jCheckBoxRepStatus.isSelected()){
           rpstatus="Yes";
       }
        StSignUpController SignUp = new StSignUpController();
        boolean res = SignUp.addRecords(userid,firstName,lastName,faculty,dp,username,password,userType,rpstatus,post,Contactdt);
        System.out.println(res);
        if(res){
            System.out.println("Successfully Inserted");
        }else{
            System.out.println("Error occured");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxRepStatus;
    private javax.swing.JComboBox<String> jCmbuserType;
    private javax.swing.JComboBox<String> jComboBoxfaculty;
    private javax.swing.JComboBox<String> jComboBoxpost;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel1RepStatus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword1Field;
    private javax.swing.JPasswordField jPassword2Field;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextMemberId;
    private javax.swing.JTextField jTextcontactnum;
    private javax.swing.JTextField jTextdegree;
    private javax.swing.JTextField jTextfname;
    private javax.swing.JTextField jTextlname;
    private javax.swing.JTextField jTextuname;
    // End of variables declaration//GEN-END:variables
}
